[project]
name = "csp-400"
version = "0.1.0"
description = "Code and content for DigiPen CSP-400"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.41.1",
    "openai-agents>=0.2.5",
    "quarto-cli>=1.7.31",
]
